urls:
  tutorial: "http://www.railstutorial.org/"
  help: "http://www.railstutorial.org/help"
  book: "https://www.railstutorial.org/book"
user:
  name:
    max_length: 50
  email:
    max_length: 255
    email_regex: "\\A[\\w+\\-.]+@[a-z\\d\\-.]+\\.[a-z]+\\z"
    case_sensitive: false
  password:
    min_length: 8
  avatar:
    gravatar_email: "http://gravatar.com/emails"
    gravatar_size: 80
    gravatar_size_user: 50
  pagy_items: 10
smtp:
  app_name: "Sample App"
  host_address: "http://127.0.0.1:3000"
  enable_starttls_auto: true
  address: 'sandbox.smtp.mailtrap.io'
  host: 'sandbox.smtp.mailtrap.io'
  port: 2525
  authentication: login
  user_name: <%= ENV['USER_EMAIL'] %>
  password: <%= ENV['USER_PASSWORD'] %>
defaults:
  time_expired: 2
  digit_140: 140
  image_types: ["image/jpeg", "image/png"]
  max_image_size: 5
  micropost_image_width: 400
  micropost_image_height: 400
micropost:
  content:
    max_length: 140
  pagy_items: 10
